data:extend(
{
    {
      type = "fluid",
      name = "planetaris-polishing-compound",
      subgroup = "fluid",
      icon = "__planetaris-hyarion__/graphics/icons/fluids/polishing-compound.png",
      icon_size = 64,
      order = "f[hyarion]-a",
      default_temperature = 10,
      max_temperature = 100,
      heat_capacity = "200J",
      base_color = {135, 129, 222},
      flow_color = {135, 129, 222},
    },
    {
      type = "fluid",
      name = "planetaris-aluminium",
      subgroup = "fluid",
      icon = "__planetaris-hyarion__/graphics/icons/fluids/aluminium.png",
      icon_size = 64,
      order = "f[hyarion]-b",
      default_temperature = 5,
      max_temperature = 50,
      heat_capacity = "50J",
      base_color = {182, 197, 240},
      flow_color = {182, 197, 240},
    },
      {
      type = "fluid",
      name = "planetaris-refraction-light",
      subgroup = "fluid",
      icon = "__planetaris-hyarion__/graphics/icons/fluids/refraction-light.png",
      icon_size = 64,
      order = "f[hyarion]-c",
      auto_barrel = false,
      default_temperature = 0,
      max_temperature = 2000000,
      heat_capacity = "1kJ",
      base_color = {255, 255, 240},
      flow_color = {255, 255, 240},
    },
    {
      type = "fluid",
      name = "planetaris-pure-light",
      subgroup = "fluid",
      icon = "__planetaris-hyarion__/graphics/icons/fluids/pure-light.png",
      icon_size = 64,
      order = "f[hyarion]-d",
      auto_barrel = false,
      default_temperature = 0,
      max_temperature = 5000000,
      heat_capacity = "5kJ",
      base_color = {255, 255, 255},
      flow_color = {255, 255, 255},
    }
})